sudo: required

services:
  - docker

before_install:
  - docker build -t sanketh1701/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sanketh1701/react-test npm test -- --coverage

after_success:
  - docker build -t sanketh1701/multi-client ./client
  - docker build -t sanketh1701/multi-nginx ./nginx
  - docker build -t sanketh1701/multi-server ./server
  - docker build -t sanketh1701/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sanketh1701/multi-client
  - docker push sanketh1701/multi-nginx
  - docker push sanketh1701/multi-server
  - docker push sanketh1701/multi-worker






